version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.3
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      TAKE_FILE_OWNERSHIP: 1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.3
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  logstash:
    image: dcm4che/logstash-dcm4chee:6.4.3-8
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "12201:12201/udp"
      - "8514:8514/udp"
      - "8514:8514"
    depends_on:
      - elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-16.1
    logging:
      driver: gelf
      options:
        gelf-address: "udp://gunter-nb:12201"
        tag: slapd
    environment:
      LDAP_URLS: "ldap:/// ldaps:///"
    ports:
      - "389:389"
      - "636:636"
    env_file: docker-compose.env
    depends_on:
      - logstash
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:5.0.0-16.1-logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://gunter-nb:12201"
        tag: keycloak
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      KEYCLOAK_WAIT_FOR: ldap:636 logstash:8514
    depends_on:
      - ldap
      - logstash
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
  keycloak-proxy:
    image: dcm4che/keycloak-proxy:4.6.0-2
    logging:
      driver: gelf
      options:
        gelf-address: "udp://gunter-nb:12201"
        tag: keycloak-proxy
    ports:
      - "8601:8601"
      - "8643:8643"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8601
      HTTPS_PORT: 8643
    depends_on:
      - kibana
      - keycloak
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
